### ISSUE TITLE
import real module when writing a mock sounds ugly

### ISSUE THREAD

**Issue by timaschew** [angular/di.js#106]
https://www.youtube.com/watch?v=_OGGsf1ZXMs#t=19m

In this example the MockHeater needs to import/require the real Heater.
But with this line of code you create a dependency from your mock to the implementation.
This sounds really wrong and can be a problem if the implementation of heater has many own dependencies.

**Comment by L8D** [comment]
What is the issue with a mock needing a reference to the original implementation? This only sounds bad to me if A) you want to do outside-in TDD where you mock the parts of the system you haven't built yet, or B) the implementation imports too many modules any for some reason those modules affect your tests.

Technically this would be impossible to get around, since whatever you are testing (in this case, the coffee brewer) still imports the original heater class in order to write the annotation `@Inject(Heater)`.

I think the best way to get around this limitation is to use standardized libraries as boundaries between your systems. For example, instead of have a view class inject an instance of the controller (requiring you to mock the controller and import it during unit testing), you can design your view class to only read from the models. The model can be either injected independently of the controller, or somehow passed as a parameter to the view class. Similarly, if you want to capture events from the view layer, and send those to the controller, you can use a mediator system like Flux’s dispatcher to create a layer of abstraction between your view and controller, and suddenly you only need to mock dispatched actions instead of entire controllers.

**Comment by timaschew** [comment]
> B) the implementation imports too many modules any for some reason those modules affect your tests.

this is exactly what I wanted to say.

> I think the best way to get around this limitation is to use standardized libraries as boundaries between your systems. For example, instead of have a view class inject an instance of the controller (requiring you to mock the controller and import it during unit testing), you can design your view class to only read from the models. The model can be either injected independently of the controller, or somehow passed as a parameter to the view class. Similarly, if you want to capture events from the view layer, and send those to the controller, you can use a mediator system like Flux’s dispatcher to create a layer of abstraction between your view and controller, and suddenly you only need to mock dispatched actions instead of entire controllers.

Yes, our MV\* architecture has some issues and we already considering to replace it with flux.
Thanks
